### ISSUE TITLE
post__not_in is not working

### ISSUE THREAD

**Issue by ghost** [dphiffer/wp-json-api#25]
Hej!

I can't get `post__not_in` parameter work when I fetch a bunch of posts. When use the following to fetch posts `www.example.com/api/get_posts/?post_type=custom_post_type&post__not_in=array(1,2,3,4,6)&count=6&offset=0`, everything works fine but the posts with the ids `1,2,3,4,5` are not excluded in the response.

What am I doing wrong here?

**Comment by jkeary** [comment]
I know its a little late for this, but for anyone in the future needing help:

<code>
excluded_posts = '';
</code>
<code>
for (var i=0; i < array_of_ids.length; i++)
</code>
<code>{</code>
<code> excluded_posts += '&post__not_in[]=' + array_of_ids[i];</code>
<code>}</code>
<code>var url = 'www.example.com/api/get_posts/post_type=custom_post_type&count=6&offset=0' + excluded_posts;
</code>
