### ISSUE TITLE
Unknown method returns 200

### ISSUE THREAD

**Issue by pdl** [dphiffer/wp-json-api#28]
GET /api/foo/
    => {"status":"error","error":"Uknown method 'foo'."}

... which is all well and good (I've put in a PR for the typo). But the response code in this case is 200, which implies some sort of success; a 4xx error (probably 404) would surely be more appropriate?

**Comment by dphiffer** [comment]
This is a good idea, thanks @pdl. This will be updated in version 1.1.2.
